# Generated by Django 5.2.6 on 2025-09-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la mascota')),
                ('nombre', models.CharField(max_length=30)),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del rol')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('rut', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('fNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=12)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Paseo',
            fields=[
                ('idPaseo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del paseo')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.IntegerField()),
                ('lugarEncuentro', models.CharField(max_length=100)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.usuario'),
        ),
    ]
